apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjenkins
spec:
  selector:
    matchLabels:
      app: myjenkins
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: jenkins/jenkins:lts
    spec:
      containers:
      - name: myjenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8083
