apiVersion: v1
kind: Service
metadata:
  name: myapprep
spec:
  ports:
  - port: 80
  selector:
    app: myapprep
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapprep
spec:
  selector:
    matchLabels:
      app: myapprep
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myapprep
    spec:
      containers:
      - name: myapp
        image: iyadomry/helloworld
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azure-myapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myapprep
